module.exports = {
  /* physical */
  physicaldata: [
    {
      root: true,
      id: "cluster_1",
      title: "Cluster1",
      method: "setCluster",
      type: "CLUSTER",
      args: "http://smc-sl-api.local/",
      children: [
        {
          id: "node_1",
          title: "Node1 (172.30.6.41)",
          method: "setNodeIP",
          "address-IP4": "172.30.6.41",
          "address-IP6": "fe80::9c9d:1e6b:92aa:2251%19",
          args: { ip: "172.30.6.41", id: "node_1" },
          address: "172.30.6.41",
          type: "NODE",
          children: [
            {
              id: "_node_1_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_1_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/services",
                
                },
                {
                  id: "_node_1_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_1_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_1_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                          children: [
                            {
                              id: "_node_1_cpu0_core0",
                              title: "CORE0",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/0",
                            },
                          ],
                        },
                        {
                          id: "_node_1_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                          children: [
                            {
                              id: "_node_1_cpu2_core1",
                              title: "CORE1",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/1",
                            },
                          ]
                        },
                      ],
                    },
                    {
                      id: "_node_1_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_1_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                          children: [
                            {
                              id: "_node_6_hdd_sda1",
                              title: "sda1",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda1",
                            },
                            {
                              id: "_node_6_hdd_sda2",
                              title: "sda2",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda2",
                            },
                          ]
                        },
                        {
                          id: "_node_1_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_1_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_1_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_1_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_1_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_1_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_1_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_1_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_1_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                    {
                      id: "_node_1_ceph",
                      title: "CEPH",
                      type: "CEPH",
                      //method: "setAPIUrl",
                      //args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_1_nic_osds",
                          title: "OSDs",
                          type: "OSDs",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/ceph/osd",
                        },
                        {
                          id: "_node_1_nic_pool",
                          title: "POOL",
                          type: "POOL",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_1_nic_lun",
                          title: "LUN",
                          type: "LUN",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                        {
                          id: "_node_1_nic_cephservices",
                          title: "CEPH SERVICES",
                          type: "CEPHSERVICES",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/ceph/ceph",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: "node_2",
          title: "Node2 (172.30.6.42)",
          method: "setNodeIP",
          args: { ip: "172.30.6.42", id: "node_2" },
          address: "172.30.6.42",
            "address-IP4": "172.30.6.42",
          "address-IP6": "fe80::9c9d:1e6b:92aa:2251%19",
          type: "NODE",
          children: [
            {
              id: "_node_2_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_2_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/services",
              
                },
                {
                  id: "_node_2_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_2_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_2_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                          children: [
                            {
                              id: "_node_2_cpu0_core0",
                              title: "CORE0",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/0",
                            },
                          ],
                        },
                        {
                          id: "_node_2_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                          children: [
                            {
                              id: "_node_2_cpu0_core1",
                              title: "CORE1",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/1",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: "_node_2_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_2_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                          children: [
                            {
                              id: "_node_6_hdd_sda1",
                              title: "sda1",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda1",
                            },
                            {
                              id: "_node_6_hdd_sda2",
                              title: "sda2",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda2",
                            },
                          ]
                        },
                        {
                          id: "_node_2_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_2_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_2_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_2_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_2_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_2_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_2_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_2_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_2_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        }, {
          id: "node_3",
          title: "Node3 (172.30.6.43)",
          method: "setNodeIP",
          args: { ip: "172.30.6.43", id: "node_3" },
          address: "172.30.6.43",
          "address-IP4": "172.30.6.43",
          "address-IP6": "fe80::9c9d:1e6b:92aa:2251%19",
          type: "NODE",
          children: [
            {
              id: "_node_3_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_3_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/services",
                
                },
                {
                  id: "_node_3_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_3_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_3_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                          children: [
                            {
                              id: "_node_3_cpu0_core0",
                              title: "CORE0",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/0",
                            },
                          ],
                        },
                        {
                          id: "_node_3_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                          children: [
                            {
                              id: "_node_3_cpu0_core1",
                              title: "CORE0",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/1",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: "_node_3_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_3_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                          children: [
                            {
                              id: "_node_6_hdd_sda1",
                              title: "sda1",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda1",
                            },
                            {
                              id: "_node_6_hdd_sda2",
                              title: "sda2",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda2",
                            },
                          ]
                        },
                        {
                          id: "_node_3_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_3_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_3_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_3_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_3_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_3_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_3_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_3_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_3_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },{
          id: "node_4",
          title: "Node4 (172.30.6.44)",
          method: "setNodeIP",
          args: { ip: "172.30.6.44", id: "node_4" },
          address: "172.30.6.44",
          type: "NODE",
          "address-IP4": "172.30.6.44",
          "address-IP6": "fe80::9c9d:1e6b:92aa:2251%19",
          children: [
            {
              id: "_node_4_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_4_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/services",
             
                },
                {
                  id: "_node_4_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_4_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_4_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                          children: [
                            {
                              id: "_node_4_cpu0_core0",
                              title: "CORE0",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/0",
                            },
                          ],
                        },
                        {
                          id: "_node_4_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                          children: [
                            {
                              id: "_node_4_cpu0_core1",
                              title: "CORE1",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/1",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: "_node_4_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_4_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                          children: [
                            {
                              id: "_node_6_hdd_sda1",
                              title: "sda1",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda1",
                            },
                            {
                              id: "_node_6_hdd_sda2",
                              title: "sda2",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda2",
                            },
                          ]
                        },
                        {
                          id: "_node_4_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_4_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_4_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_4_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_4_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_4_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_4_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_4_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_4_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },{
          id: "node_5",
          title: "Node5 (172.30.6.45)",
          method: "setNodeIP",
          args: { ip: "172.30.6.45", id: "node_5" },
          address: "172.30.6.45",
          type: "NODE",
          "address-IP4": "172.30.6.45",
          "address-IP6": "fe80::9c9d:1e6b:92aa:2251%19",
          children: [
            {
              id: "_node_5_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_5_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/services",
              
                },
                {
                  id: "_node_5_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_5_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_5_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                          children: [
                            {
                              id: "_node_5_cpu0_core0",
                              title: "CORE0",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/0",
                            },
                          ],
                        },
                        {
                          id: "_node_5_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                          children: [
                            {
                              id: "_node_5_cpu0_core1",
                              title: "CORE1",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/1",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: "_node_5_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_5_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                          children: [
                            {
                              id: "_node_6_hdd_sda1",
                              title: "sda1",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda1",
                            },
                            {
                              id: "_node_6_hdd_sda2",
                              title: "sda2",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda2",
                            },
                          ]
                        },
                        {
                          id: "_node_5_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_5_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_5_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_5_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_5_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_5_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_5_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_5_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_5_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },{
          id: "node_6",
          title: "Node6 (172.30.6.46)",
          method: "setNodeIP",
          args: { ip: "172.30.6.46", id: "node_6" },
          address: "172.30.6.46",
          "address-IP4": "172.30.6.41",
          "address-IP6": "fe80::9c9d:1e6b:92aa:2251%19",
          type: "NODE",
          children: [
            {
              id: "_node_6_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_6_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/services",
                
                },
                {
                  id: "_node_6_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_6_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_6_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                          children: [
                            {
                              id: "_node_6_cpu0_core0",
                              title: "CORE0",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/0",
                            },
                             {
                              id: "_node_6_cpu0_core1",
                              title: "CORE1",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/1",
                            },
                          ],
                        },
                        {
                          id: "_node_6_cpu1",
                          title: "CPU1",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/1",
                          children: [
                            {
                              id: "_node_6_cpu1_core1",
                              title: "CORE2",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/2",
                            },
                            {
                              id: "_node_6_cpu1_core2",
                              title: "CORE3",
                              type: "CORE",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/core/3",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: "_node_6_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_6_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                          children: [
                            {
                              id: "_node_6_hdd_sda1",
                              title: "sda1",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda1",
                            },
                            {
                              id: "_node_6_hdd_sda2",
                              title: "sda2",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda2",
                            },
                          ]
                        },
                        {
                          id: "_node_6_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_6_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_6_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_6_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_6_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_6_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_6_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_6_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_6_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },{
          id: "node_8",
          title: "Node7 (172.30.6.48)",
          method: "setNodeIP",
          args: { ip: "172.30.6.48", id: "node_8" },
          address: "172.30.6.48",
          "address-IP4": "172.30.6.41",
          "address-IP6": "fe80::9c9d:1e6b:92aa:2251%19",
          type: "NODE",
          children: [
            {
              id: "_node_8_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_8_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/services",
             
                },
                {
                  id: "_node_8_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_8_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_8_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                        },
                        {
                          id: "_node_8_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                        },
                      ],
                    },
                    {
                      id: "_node_8_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_8_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                          children: [
                            {
                              id: "_node_6_hdd_sda1",
                              title: "sda1",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda1",
                            },
                            {
                              id: "_node_6_hdd_sda2",
                              title: "sda2",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda2",
                            },
                          ]
                        },
                        {
                          id: "_node_8_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_8_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_8_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_8_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_8_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_8_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_8_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_8_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_8_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },{
          id: "node_9",
          title: "Node8 (172.30.6.49)",
          method: "setNodeIP",
          args: { ip: "172.30.6.49", id: "node_9" },
          address: "172.30.6.49",
          type: "NODE",
          "address-IP4": "172.30.6.41",
          "address-IP6": "fe80::9c9d:1e6b:92aa:2251%19",
          children: [
            {
              id: "_node_9_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_9_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/services",
               
                },
                {
                  id: "_node_9_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_9_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_9_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                        },
                        {
                          id: "_node_9_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                        },
                      ],
                    },
                    {
                      id: "_node_9_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_9_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                          children: [
                            {
                              id: "_node_6_hdd_sda1",
                              title: "sda1",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda1",
                            },
                            {
                              id: "_node_6_hdd_sda2",
                              title: "sda2",
                              type: "HDD",
                              method: "setAPIUrl",
                              args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/partition/sda2",
                            },
                          ]
                        },
                        {
                          id: "_node_9_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_9_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_9_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_9_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_9_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_9_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_9_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_9_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_9_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  /* logical */
  logicaldata: [
    {
      root: true,
      id: "ceph_1",
      title: "CEPH",
      method: null,
      type: "CLUSTER",
      args: null,
      children: [
        {
          id: "osds",
          title: "OSDs",
          address: "172.30.6.41",
          type: "NODE",
        }
      ]
    }
  ],
};
