module.exports = {
  /* physical */
  physicaldata: [
    {
      root: true,
      id: "cluster_1",
      title: "Cluster1",
      method: "setCluster",
      type: "CLUSTER",
      args: "http://smc-sl-api.local/",
      children: [
        {
          id: "node_1",
          title: "Node1",
          method: "setNodeIP",
          args: { ip: "172.30.6.41", id: "node_1" },
          address: "172.30.6.41",
          type: "NODE",
          children: [
            {
              id: "_node_1_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_1_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service",
                  children: [
                    {
                      id: "_node_1_service_1",
                      title: "auditd",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/auditd.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_1_service_2",
                      title: "chronyd",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/chronyd.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_1_service_3",
                      title: "cloud-init-local",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/cloud-init-local.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_1_service_4",
                      title: "cpupower",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/cpupower.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_1_service_5",
                      title: "crond",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/crond.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_1_service_6",
                      title: "dbus",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/dbus.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_1_service_7",
                      title: "display-manager",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/display-manager.service",
                      type: "SERVICE",
                    },
                  ],
                },
                {
                  id: "_node_1_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_1_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_1_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                        },
                        {
                          id: "_node_1_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                        },
                      ],
                    },
                    {
                      id: "_node_1_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_1_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                        },
                        {
                          id: "_node_1_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_1_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_1_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_1_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_1_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_1_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_1_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_1_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_1_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: "node_2",
          title: "Node2",
          method: "setNodeIP",
          args: { ip: "172.30.6.42", id: "node_2" },
          address: "172.30.6.42",
          type: "NODE",
          children: [
            {
              id: "_node_2_os",
              title: "OS",
              type: "OS",
              children: [
                {
                  id: "_node_2_services",
                  title: "Services",
                  method: "setAPIUrl",
                  type: "SERVICES",
                  args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service",
                  children: [
                    {
                      id: "_node_2_service_1",
                      title: "auditd",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/auditd.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_2_service_2",
                      title: "chronyd",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/chronyd.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_2_service_3",
                      title: "cloud-init-local",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/cloud-init-local.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_2_service_4",
                      title: "cpupower",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/cpupower.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_2_service_5",
                      title: "crond",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/crond.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_2_service_6",
                      title: "dbus",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/dbus.service",
                      type: "SERVICE",
                    },
                    {
                      id: "_node_2_service_7",
                      title: "display-manager",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/service/display-manager.service",
                      type: "SERVICE",
                    },
                  ],
                },
                {
                  id: "_node_2_hardwares",
                  title: "Hardwares",
                  type: "HARDWARES",
                  children: [
                    {
                      id: "_node_2_cpus",
                      title: "CPUs",
                      type: "CPUS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu",
                      children: [
                        {
                          id: "_node_2_cpu0",
                          title: "CPU0",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/0",
                        },
                        {
                          id: "_node_2_cpu2",
                          title: "CPU2",
                          type: "CPU",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/cpu/2",
                        },
                      ],
                    },
                    {
                      id: "_node_2_hdds",
                      title: "HDDs",
                      type: "HDDS",
                      children: [
                        {
                          id: "_node_2_hdd_sda",
                          title: "sda",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sda",
                        },
                        {
                          id: "_node_2_hdd_sdb",
                          title: "sdb",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdb",
                        },
                        {
                          id: "_node_2_hdd_sdc",
                          title: "sdc",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdc",
                        },
                        {
                          id: "_node_2_hdd_sdd",
                          title: "sdd",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdd",
                        },
                        {
                          id: "_node_2_hdd_sde",
                          title: "sde",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sde",
                        },
                        {
                          id: "_node_2_hdd_sdf",
                          title: "sdf",
                          type: "HDD",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/hdd/sdf",
                        },
                      ],
                    },
                    {
                      id: "_node_2_nics",
                      title: "NICs",
                      type: "NICS",
                      method: "setAPIUrl",
                      args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic",
                      children: [
                        {
                          id: "_node_2_nic_ens192",
                          title: "ens192",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens192",
                        },
                        {
                          id: "_node_2_nic_ens224",
                          title: "ens224",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/ens224",
                        },
                        {
                          id: "_node_2_nic_lo",
                          title: "lo",
                          type: "NIC",
                          method: "setAPIUrl",
                          args: "http://smc-sl-api.local/smc-sl/api/v1/oshw/nic/lo",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
